language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - jruby-1.7
  - jruby-9.0.3.0
  - jruby-head
before_install:
  - gem update --system
  - gem install bundler
sudo: false
cache: bundler
